using Microsoft.OpenApi;
using Scalar.AspNetCore;

namespace SiteManagement.Api.Configuration;

/// <summary>
/// OpenAPI + Scalar wiring. The OpenAPI document is generated by the built-in
/// <c>Microsoft.AspNetCore.OpenApi</c> services; Scalar consumes it for the
/// developer-facing docs UI.
/// </summary>
public static class OpenApiExtensions
{
    private const string ScalarUiTitle = "SiteManagement API";
    private const string BearerDescription = "Paste a JWT issued by the /api/auth endpoints.";
    private const string BearerScheme = "bearer";
    private const string BearerFormat = "JWT";

    /// <summary>
    /// Adds OpenAPI document generation. Adds a Bearer security scheme to the
    /// document so Scalar's auth panel knows how to send the token.
    /// </summary>
    public static IServiceCollection AddSiteManagementOpenApi(this IServiceCollection services)
    {
        services.AddOpenApi(options =>
        {
            options.AddDocumentTransformer((document, _, _) =>
            {
                document.Components ??= new OpenApiComponents();
                document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
                document.Components.SecuritySchemes[ApiConstants.BearerSchemeName] = new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.Http,
                    Scheme = BearerScheme,
                    BearerFormat = BearerFormat,
                    Description = BearerDescription,
                };

                return Task.CompletedTask;
            });
        });

        return services;
    }

    /// <summary>Maps the OpenAPI JSON endpoint and the Scalar UI under <c>/scalar/v1</c>.</summary>
    public static IEndpointRouteBuilder MapSiteManagementOpenApi(this IEndpointRouteBuilder app)
    {
        app.MapOpenApi();
        app.MapScalarApiReference(options =>
        {
            options.Title = ScalarUiTitle;
            options.AddPreferredSecuritySchemes(ApiConstants.BearerSchemeName);
        });

        return app;
    }
}
